[MACHINE_LEARNING_PARAMS]
DATA_SUBSET_OPTION = "False"
DATA_SUBSET_NUMBER = 5000
BATCH_SIZE = 32
HYPERPARAMETER_BATCH_SIZE = 32
OPTIM_EPOCHS = 50
N_TRIALS = 10
TRAIN_EPOCHS = 100
MIN_LAYERS = 1
MAX_LAYERS = 100
LAYER_UNITS_MIN = 2
LAYER_UNITS_MAX = 200
DROPOUT_MIN = 0.05
DROPOUT_MAX = 0.4
DROP_OUT_STEP = 0.05
LEARNING_RATE_MIN = 1e-5
LEARNING_RATE_MAX = 0.1
OPTIMIZER_LIST = [ "Adam", "RMSprop", "SGD" ]
METRIC = "loss"
DIRECTION = "minimize"
SHUFFLE = "False"
